[package]
name = "picturify-processing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
picturify-core = { path = "../core" }
thiserror = "1.0.58"
rayon = "1.10.0"
palette = "0.7.5"