[package]
name = "picturify-pipeline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
picturify-processing.workspace = true
picturify-core.workspace = true
log = "0.4.21"
