[package]
name = "picturify-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image.workspace = true
palette.workspace = true
rayon.workspace = true
thiserror.workspace = true
log = "0.4.21"