[package]
name = "picturify-testing"
version = "0.1.0-alpha"
authors = ["81999946+sobczal2@users.noreply.github.com"]
edition = "2021"

[dependencies]
uuid.workspace = true
assert_cmd.workspace = true